### ISSUE TITLE
NameError: name 'benchmark' is not defined

### ISSUE THREAD

**Issue by MinuteswithMetrics** [TharinduDR/Siamese-Recurrent-Architectures#7]
I am trying to run your code on a different dataset and keep running into the `NameError: name 'benchmark' is not defined`. Where can I define benchmark?

**Comment by TharinduDR** [comment]
Hi @MinuteswithMetrics, 

If you see the notebooks you will see that I define benchmarks like this - 
`benchmarks = [("LSTM-W2V-ADADELTA",
               ft.partial(run_lstm_benchmark, validation_portion=validation_portion, n_hidden=n_hidden,
                          embedding_dim=embedding_dim, batch_size=batch_size, n_epoch=n_epoch, optimizer=adadelta,
                          model=word2vec)),
              ("LSTM-GLOVE-ADADELTA",
               ft.partial(run_lstm_benchmark, validation_portion=validation_portion, n_hidden=n_hidden,
                          embedding_dim=embedding_dim, batch_size=batch_size, n_epoch=n_epoch, optimizer=adadelta,
                          model=glove)),
              ("LSTM-FASTTEXT-ADADELTA",
               ft.partial(run_lstm_benchmark, validation_portion=validation_portion, n_hidden=n_hidden,
                          embedding_dim=embedding_dim, batch_size=batch_size, n_epoch=n_epoch, optimizer=adadelta,
                          model=fasttext))]`
